PUT http://localhost:3003/api/blogs/6294b325e84b7996566ff9c7
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphbmUyNyIsImlkIjoiNjI5MzRmZTkzNDI1YzJlMjMyNGUxYjM0IiwiaWF0IjoxNjUzODQ0MTExfQ.TZrxRp5EURjzYKbbqPw0vB1Ne2huFZdnTppOJJuCr9c

{
    "title": "Jane's favourite tea",
    "author": "Jane Grusten",
    "url": "www.janeausten.com/tea",
    "likes": 3,
    "user": "62934fe93425c2e2324e1b34",
    "id": "6293b02cc427c26f092e94d5"
}


###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "Hello",
    "author": "Jane Grusten",
    "url": "www.janeausten.com",
    "likes": 7
}


###
post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtldmluMDkiLCJpZCI6IjYyOTczMjZmNDRkNTVmOTM0ZGMwYWI2NiIsImlhdCI6MTY1NDA3NjIzN30.op9vOOm8IPABjCgGGgWWb717Igk4MGd2wqEhiOSFS24

{
    "title": "Test blog by Jane!!",
    "author": "Jane Grusten",
    "url": "www.janeausten.com/tea",
    "likes": 2
}

### deletion right user
DELETE http://localhost:3003/api/blogs/6293bc3ee3576e134b5d99c1 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphbmUyNyIsImlkIjoiNjI5MzRmZTkzNDI1YzJlMjMyNGUxYjM0IiwiaWF0IjoxNjUzODQ0MTExfQ.TZrxRp5EURjzYKbbqPw0vB1Ne2huFZdnTppOJJuCr9c

### deletion wrong user
DELETE http://localhost:3003/api/blogs/6293bc3ee3576e134b5d99c1 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4yNyIsImlkIjoiNjI5M2FlYWRjZTQyMzRlMmYxMjU3MmQ3IiwiaWF0IjoxNjUzODQ1NzA4fQ.stQ_o1SF9Zjpo4lwjrHTHovdPlJVm_SWCpfoODb8XpY

### deletion no token
DELETE http://localhost:3003/api/blogs/6293ae43ce4234e2f12572d3 HTTP/1.1
